version: "2"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    container_name: broker
    image: docker.io/bitnami/kafka:2
    ports:
      - "9092:9092"
      - "29092:29092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_ADVERTISED_LISTENERS=LISTENER_OUT://localhost:9092,LISTENER_IN://broker:29092
      - KAFKA_LISTENERS=LISTENER_OUT://broker:9092,LISTENER_IN://broker:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=LISTENER_OUT:PLAINTEXT,LISTENER_IN:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=LISTENER_IN
    depends_on:
      - zookeeper

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
